(function(){function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function q(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}var ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},r;
if("function"==typeof Object.setPrototypeOf)r=Object.setPrototypeOf;else{var t;a:{var ca={Aa:!0},da={};try{da.__proto__=ca;t=da.Aa;break a}catch(a){}t=!1}r=t?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var v=r;
function w(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(v)v(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,c);e&&Object.defineProperty(a,c,e)}else a[c]=b[c];a.Cb=b.prototype}var x="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},z="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;
function ea(){ea=function(){};z.Symbol||(z.Symbol=fa)}function ha(a,b){this.a=a;x(this,"description",{configurable:!0,writable:!0,value:b})}ha.prototype.toString=function(){return this.a};var fa=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new ha("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();
function A(){ea();var a=z.Symbol.iterator;a||(a=z.Symbol.iterator=z.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&x(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ia(aa(this))}});A=function(){}}function ia(a){A();a={next:a};a[z.Symbol.iterator]=function(){return this};return a}function B(){this.i=!1;this.f=null;this.b=void 0;this.a=1;this.Y=this.H=0;this.g=null}function C(a){if(a.i)throw new TypeError("Generator is already running");a.i=!0}
B.prototype.A=function(a){this.b=a};function D(a,b){a.g={Ka:b,Va:!0};a.a=a.H||a.Y}B.prototype.return=function(a){this.g={return:a};this.a=this.Y};function E(a,b,c){a.a=c;return{value:b}}function ja(a){this.a=new B;this.b=a}function ka(a,b){C(a.a);var c=a.a.f;if(c)return F(a,"return"in c?c["return"]:function(e){return{value:e,done:!0}},b,a.a.return);a.a.return(b);return G(a)}
function F(a,b,c,e){try{var h=b.call(a.a.f,c);if(!(h instanceof Object))throw new TypeError("Iterator result "+h+" is not an object");if(!h.done)return a.a.i=!1,h;var f=h.value}catch(d){return a.a.f=null,D(a.a,d),G(a)}a.a.f=null;e.call(a.a,f);return G(a)}function G(a){for(;a.a.a;)try{var b=a.b(a.a);if(b)return a.a.i=!1,{value:b.value,done:!1}}catch(c){a.a.b=void 0,D(a.a,c)}a.a.i=!1;if(a.a.g){b=a.a.g;a.a.g=null;if(b.Va)throw b.Ka;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function la(a){this.next=function(b){C(a.a);a.a.f?b=F(a,a.a.f.next,b,a.a.A):(a.a.A(b),b=G(a));return b};this.throw=function(b){C(a.a);a.a.f?b=F(a,a.a.f["throw"],b,a.a.A):(D(a.a,b),b=G(a));return b};this.return=function(b){return ka(a,b)};A();this[Symbol.iterator]=function(){return this}}function H(a,b){b=new la(new ja(b));v&&v(b,a.prototype);return b}
function I(a,b){if(b){var c=z;a=a.split(".");for(var e=0;e<a.length-1;e++){var h=a[e];h in c||(c[h]={});c=c[h]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&x(c,a,{configurable:!0,writable:!0,value:b})}}
I("Promise",function(a){function b(d){this.b=0;this.i=void 0;this.a=[];var k=this.f();try{d(k.resolve,k.reject)}catch(m){k.reject(m)}}function c(){this.a=null}function e(d){return d instanceof b?d:new b(function(k){k(d)})}if(a)return a;c.prototype.b=function(d){if(null==this.a){this.a=[];var k=this;this.f(function(){k.i()})}this.a.push(d)};var h=z.setTimeout;c.prototype.f=function(d){h(d,0)};c.prototype.i=function(){for(;this.a&&this.a.length;){var d=this.a;this.a=[];for(var k=0;k<d.length;++k){var m=
d[k];d[k]=null;try{m()}catch(l){this.g(l)}}}this.a=null};c.prototype.g=function(d){this.f(function(){throw d;})};b.prototype.f=function(){function d(l){return function(g){m||(m=!0,l.call(k,g))}}var k=this,m=!1;return{resolve:d(this.eb),reject:d(this.g)}};b.prototype.eb=function(d){if(d===this)this.g(new TypeError("A Promise cannot resolve to itself"));else if(d instanceof b)this.lb(d);else{a:switch(typeof d){case "object":var k=null!=d;break a;case "function":k=!0;break a;default:k=!1}k?this.Xa(d):
this.A(d)}};b.prototype.Xa=function(d){var k=void 0;try{k=d.then}catch(m){this.g(m);return}"function"==typeof k?this.mb(k,d):this.A(d)};b.prototype.g=function(d){this.H(2,d)};b.prototype.A=function(d){this.H(1,d)};b.prototype.H=function(d,k){if(0!=this.b)throw Error("Cannot settle("+d+", "+k+"): Promise already settled in state"+this.b);this.b=d;this.i=k;this.Y()};b.prototype.Y=function(){if(null!=this.a){for(var d=0;d<this.a.length;++d)f.b(this.a[d]);this.a=null}};var f=new c;b.prototype.lb=function(d){var k=
this.f();d.T(k.resolve,k.reject)};b.prototype.mb=function(d,k){var m=this.f();try{d.call(k,m.resolve,m.reject)}catch(l){m.reject(l)}};b.prototype.then=function(d,k){function m(p,u){return"function"==typeof p?function(y){try{l(p(y))}catch(V){g(V)}}:u}var l,g,n=new b(function(p,u){l=p;g=u});this.T(m(d,l),m(k,g));return n};b.prototype.catch=function(d){return this.then(void 0,d)};b.prototype.T=function(d,k){function m(){switch(l.b){case 1:d(l.i);break;case 2:k(l.i);break;default:throw Error("Unexpected state: "+
l.b);}}var l=this;null==this.a?f.b(m):this.a.push(m)};b.resolve=e;b.reject=function(d){return new b(function(k,m){m(d)})};b.race=function(d){return new b(function(k,m){for(var l=q(d),g=l.next();!g.done;g=l.next())e(g.value).T(k,m)})};b.all=function(d){var k=q(d),m=k.next();return m.done?e([]):new b(function(l,g){function n(y){return function(V){p[y]=V;u--;0==u&&l(p)}}var p=[],u=0;do p.push(void 0),u++,e(m.value).T(n(p.length-1),g),m=k.next();while(!m.done)})};return b});
var ma="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var e=arguments[c];if(e)for(var h in e)Object.prototype.hasOwnProperty.call(e,h)&&(a[h]=e[h])}return a};I("Object.assign",function(a){return a||ma});I("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});
I("Array.prototype.includes",function(a){return a?a:function(b,c){var e=this;e instanceof String&&(e=String(e));var h=e.length;c=c||0;for(0>c&&(c=Math.max(c+h,0));c<h;c++){var f=e[c];if(f===b||Object.is(f,b))return!0}return!1}});
var na={Ha:"connect_debug",Da:"https://signal-beacon.s-onetag.com/beacon.min.js",ob:"https://ap.lijit.com/readerinfo/v2",ab:"https://get.s-onetag.com/container-polyfills.js",$a:["fetch","Promise"],Ra:"https://onetag-geo.s-onetag.com/",sb:"https://onetag-geo-grouping.s-onetag.com/",tb:"https://geo-location.s-onetag.com/",Pa:86400,Oa:200,yb:"EU",fa:10,ka:"https://ap.lijit.com/www/delivery/fpi.js?z=",nb:"https://gam-ad-unit-inspector.s-onetag.com/",va:{Ta:"https://get.s-onetag.com/safeframe-urls/1.0.0/safe-frame-internal.html",
Wa:"https://get.s-onetag.com/safeframe-urls/1.0.0/safe-frame.js"},Ab:"https://prebid.s-onetag.com",ba:"https://dfp-gateway.s-onetag.com/1",ea:86400,la:"https://connect-metrics-collector.s-onetag.com/metrics",Db:5E3,zb:"https://get.s-onetag.com/underground-sync-portal/Portal.html",qb:"https://data-beacons.s-onetag.com/dataBeacons.min.js",ub:["hb_","ix_","amznp","amznbid"],xb:7E3};var J;function K(){if(J)return J;throw Error("Not initialized");};function oa(){this.window=window}var L;function M(){L||(L=new oa);return L}oa.prototype.get=function(){var a=this.window.top;try{a=pa(a),a.__connect.state="FRIENDLY"}catch(b){a=pa(this.window),a.__connect.state="UNFRIENDLY",a.ja&&a.ja.ext&&(a.__connect.state="SAFEFRAME")}return a};function pa(a){a.__connect||(a.__connect={});return a};var qa=this&&this.a||function(a,b,c,e){function h(f){return f instanceof c?f:new c(function(d){d(f)})}return new (c||(c=Promise))(function(f,d){function k(g){try{l(e.next(g))}catch(n){d(n)}}function m(g){try{l(e["throw"](g))}catch(n){d(n)}}function l(g){g.done?f(g.value):h(g.value).then(k,m)}l((e=e.apply(a,b||[])).next())})};function ra(){this.window=M().get();this.j=K()}function sa(){N||(N=new ra);return N}
function ta(a,b){qa(a,void 0,void 0,function e(){var h=this,f;return H(e,function(d){f=h;h.window.__connect=h.window.__connect||{};h.window.__connect.beacon=h.window.__connect.beacon||{containerId:b.containerId,affiliateId:b.G,disablePIITracking:!!b.ma};return d.return(new Promise(function(k){var m=f.window.document.createElement("script");m.onload=function(){k()};m.src=f.j.Da;f.window.document.head.appendChild(m)}))})})}
function ua(a,b,c,e){b=void 0===b?0:b;if(a.window.__connect){var h=a.window.__connect.affiliateIds;if(h&&h[b])h[b](c,e);else setTimeout(function(){ua(a,b,c,e)},1E3)}}var N=null;function va(a){this.a=a}va.prototype.create=function(a){return new this.a[a.Na](a.c)};var wa=this&&this.a||function(a,b,c,e){function h(f){return f instanceof c?f:new c(function(d){d(f)})}return new (c||(c=Promise))(function(f,d){function k(g){try{l(e.next(g))}catch(n){d(n)}}function m(g){try{l(e["throw"](g))}catch(n){d(n)}}function l(g){g.done?f(g.value):h(g.value).then(k,m)}l((e=e.apply(a,b||[])).next())})};function xa(a){this.Ma=new va(a)}
function ya(a,b){return wa(a,void 0,void 0,function e(){var h=this,f,d,k,m,l,g;return H(e,function(n){switch(n.a){case 1:if(!b||0===b.length)return n.return(!0);f=za(b);d=[];k=q(Object.keys(f));m=k.next();case 2:if(m.done){n.a=4;break}l=m.value;return E(n,Aa(h,f[l]),5);case 5:g=n.b;d.push(g);m=k.next();n.a=2;break;case 4:return n.return(d.every(function(p){return p}))}})})}
function Aa(a,b){return wa(a,void 0,void 0,function e(){var h=this,f,d,k,m,l,g,n;return H(e,function(p){switch(p.a){case 1:f="EXCLUDE"===b[0].c.cb,d=q(b),k=d.next();case 2:if(k.done){p.a=4;break}m=k.value;l=h.Ma.create(m);return E(p,l.wb(),5);case 5:g=p.b;n=m.c.cb;f="EXCLUDE"===n?f&&!g:f||g;k=d.next();p.a=2;break;case 4:return p.return(f)}})})}function za(a){return a.reduce(function(b,c){var e=c.Na;b[e]||(b[e]=[]);b[e].push(c);return b},{})};M().get();function Ba(){this.s=!0};function O(a){this.s=!0;this.window=a;this.window.addEventListener("focus",this.b.bind(this));this.window.addEventListener("focusin",this.b.bind(this));this.window.addEventListener("blur",this.a.bind(this));this.window.addEventListener("focusout",this.a.bind(this))}w(O,Ba);O.prototype.b=function(){this.s=!0};O.prototype.a=function(){this.window.document.hasFocus()?this.s=!0:this.s=!1};function P(a,b){this.s=!0;this.window=a;this.f=void 0===b?10:b;this.i="mousemove mousedown scroll keyup keypress keydown touchstart touchmove touchend".split(" ");a=q(this.i);for(b=a.next();!b.done;b=a.next())this.window.addEventListener(b.value,this.a.bind(this));this.a()}w(P,Ba);P.prototype.a=function(){var a=this;this.b||(this.b=this.window.setTimeout(function(){clearTimeout(a.A);a.A=a.window.setTimeout(a.g.bind(a),1E3*a.f);a.b=null},50),this.s=!0)};P.prototype.g=function(){this.s=!1};function Ca(a,b){this.a=a;this.b=b}var Q;function Da(){if(!Q){var a=M().get(),b=new O(a);a=new P(a);Q=new Ca(b,a)}return Q}Ca.prototype.s=function(){return this.a.s&&this.b.s};function Ea(){}Ea.prototype.create=function(){return new XMLHttpRequest};function Fa(){this.a=new Ea}Fa.prototype.send=function(a,b){var c=this.a.create();c.open("POST",a,!1);c.setRequestHeader("Content-Type","text/plain");c.send(JSON.stringify(b))};function Ga(a,b){a=Error.call(this,JSON.stringify(b));this.message=a.message;"stack"in a&&(this.stack=a.stack)}w(Ga,Error);var Ha=this&&this.a||function(a,b,c,e){function h(f){return f instanceof c?f:new c(function(d){d(f)})}return new (c||(c=Promise))(function(f,d){function k(g){try{l(e.next(g))}catch(n){d(n)}}function m(g){try{l(e["throw"](g))}catch(n){d(n)}}function l(g){g.done?f(g.value):h(g.value).then(k,m)}l((e=e.apply(a,b||[])).next())})};function Ia(){}
function Ja(a,b){var c=void 0===c?{}:c;return Ha(a,void 0,void 0,function h(){var f,d,k;return H(h,function(m){if(1==m.a)return E(m,fetch(b,c),2);if(3!=m.a)return f=m.b,E(m,f.json(),3);d=m.b;k=f.status.toString();if("4"===k[0]||"5"===k[0])throw new Ga(k,d);return m.return(d)})})};var Ka=this&&this.a||function(a,b,c,e){function h(f){return f instanceof c?f:new c(function(d){d(f)})}return new (c||(c=Promise))(function(f,d){function k(g){try{l(e.next(g))}catch(n){d(n)}}function m(g){try{l(e["throw"](g))}catch(n){d(n)}}function l(g){g.done?f(g.value):h(g.value).then(k,m)}l((e=e.apply(a,b||[])).next())})};function La(){this.j=K();this.window=M().get();this.da=new Ia;this.U=!1}var Ma;
function Na(a){return Ka(a,void 0,void 0,function c(){var e=this,h,f;return H(c,function(d){switch(d.a){case 1:try{var k=JSON.parse(e.window.localStorage.getItem("connect-location"));var m=k.expiresAt>Date.now()?k.value:!1}catch(l){m=!1}if(h=m)return d.return(h);if(!e.U){d.a=2;break}return E(d,e.wait(e.j.Oa),3);case 3:return d.return(Na(e));case 2:return e.U=!0,E(d,Oa(e),4);case 4:return f=d.b,e.ha("connect-location",f),e.U=!1,d.return(f)}})})}
function Oa(a){return Ka(a,void 0,void 0,function c(){var e=this,h;return H(c,function(f){if(1==f.a)return E(f,Ja(e.da,e.j.Ra),2);h=f.b;if(!h.country)throw e.U=!1,Error("Location not found");return f.return(h.country)})})}La.prototype.ha=function(a,b){b={value:b,expiresAt:Date.now()+1E3*this.j.Pa};try{this.window.localStorage.setItem(a,JSON.stringify(b))}catch(c){}};
La.prototype.wait=function(a){return Ka(this,void 0,void 0,function c(){return H(c,function(e){return e.return(new Promise(function(h){return setTimeout(h,a)}))})})};var Pa=function(){function a(){}a.Sa=function(){var b=M().get();b=b[a.a]=b[a.a]||{};b.pageViewId||(b.pageViewId=a.b());return b.pageViewId};a.b=function(){return+new Date+Math.floor(1E3*Math.random())};a.a="__connect";return a}();var Qa=this&&this.a||function(a,b,c,e){function h(f){return f instanceof c?f:new c(function(d){d(f)})}return new (c||(c=Promise))(function(f,d){function k(g){try{l(e.next(g))}catch(n){d(n)}}function m(g){try{l(e["throw"](g))}catch(n){d(n)}}function l(g){g.done?f(g.value):h(g.value).then(k,m)}l((e=e.apply(a,b||[])).next())})};
function Ra(){Ma||(Ma=new La);this.Qa=Ma;this.window=M().get();this.Z={pageViewId:Pa.Sa(),domain:this.window.location.hostname,path:this.window.location.pathname,isSafeFrame:this.v(),location:"",query:this.window.location.search.slice(0,100)};Sa(this)}Ra.prototype.get=function(){return this.Z};function Sa(a){Qa(a,void 0,void 0,function c(){var e=this,h;return H(c,function(f){h=e;Na(e.Qa).then(function(d){h.Z.location=d});f.a=0})})}Ra.prototype.v=function(){return"FRIENDLY"!==this.window.__connect.state};function R(){this.L=[];this.g={};this.a=!1;this.j=K();this.i=Da();this.window=M().get();this.H=new Ra;this.A=new Fa;this.ia()}var Ta;function Ua(){Ta||(Ta=new R);return Ta}function Va(a,b,c){a.g[b]||(a.g[b]=!0,a.L.push(Object.assign({},{containerId:b,type:"adoption"})));c&&a.L.push(Object.assign({},{containerId:b,contentId:c,type:"adoption"}))}R.prototype.ia=function(){var a=this;Wa(this);this.window.setInterval(function(){a.i.s()||Xa(a)},1E3)};
function Wa(a){a.window.addEventListener("pageshow",a.b.bind(a));a.window.addEventListener("beforeunload",a.f.bind(a));a.window.addEventListener("pagehide",a.f.bind(a));a.window.document.addEventListener("visibilitychange",function(){if(a.window.document.hidden)return a.f();a.b()})}R.prototype.f=function(){this.a||(this.a=!0,Xa(this),this.window.setTimeout(this.b.bind(this),3E3))};R.prototype.b=function(){this.a=!1};
function Xa(a){if(a.L.length){var b=a.window.navigator,c={metadata:a.H.get(),payloads:a.L};a.L=[];var e=!1;b.sendBeacon&&(e=b.sendBeacon(a.j.la,JSON.stringify(c)));e||a.A.send(a.j.la,JSON.stringify(c))}};var Ya=this&&this.a||function(a,b,c,e){function h(f){return f instanceof c?f:new c(function(d){d(f)})}return new (c||(c=Promise))(function(f,d){function k(g){try{l(e.next(g))}catch(n){d(n)}}function m(g){try{l(e["throw"](g))}catch(n){d(n)}}function l(g){g.done?f(g.value):h(g.value).then(k,m)}l((e=e.apply(a,b||[])).next())})};function Za(a,b){this.m=a;this.Ea=b;this.S=[];this.P=Ua();this.window=M().get();this.na=new xa(b)}
Za.prototype.start=function(){return Ya(this,void 0,void 0,function b(){var c=this,e,h,f,d,k,m,l;return H(b,function(g){switch(g.a){case 1:e=q(c.m.groups),h=e.next();case 2:if(h.done){g.a=4;break}f=h.value;return E(g,ya(c.na,f.filters),5);case 5:d=g.b;if(!d){g.a=3;break}k=q(f.Fa);m=k.next();case 7:if(m.done){g.a=3;break}l=m.value;return E(g,$a(c,l),8);case 8:m=k.next();g.a=7;break;case 3:h=e.next();g.a=2;break;case 4:c.S.length&&ab(c),g.a=0}})})};
function $a(a,b){return Ya(a,void 0,void 0,function e(){var h=this,f,d,k;return H(e,function(m){if(1==m.a)return E(m,ya(h.na,b.filters),2);f=m.b;if(!f)return m.return();var l=b.contentType,g=b.c,n=b.o,p=h.m.containerId;g.G=h.m.xa.G;d=new h.Ea[l](g,n,p);k=b.o;d.La?bb(h,d,h.m.containerId,k):"loading"!==h.window.document.readyState?bb(h,d,h.m.containerId,k):h.S.push({implementation:d,id:k});m.a=0})})}
function ab(a){a.window.document.addEventListener("readystatechange",function(){if("loading"!==a.window.document.readyState){for(var b=q(a.S),c=b.next();!c.done;c=b.next())c=c.value,bb(a,c.implementation,a.m.containerId,c.id);a.S=[]}})}function bb(a,b,c,e){Va(a.P,c,e);b.ib.start(b.ya.bind(b))};function cb(){var a={xa:{Eb:"0726e0bf-ff1a-4955-b67e-a42905da4c6c",G:251676},containerId:"de8d3c3f-602a-4921-94f6-6c06fb8d9728",groups:[{groupId:"86454e3b-6352-4093-94c9-c86863d81b2d",enabled:!0,filters:[],c:{},Fa:[{o:"5bbe1572-e670-4415-af24-ac85aeba0d5e",filters:[],c:{width:336,height:280,u:658521,I:"",B:20,F:!0,v:!1,C:!1,D:!1,O:!1,l:[]},contentType:"signal-sovrn",enabled:!0},{o:"2266180a-4372-4302-a9c2-3d5533deb70d",filters:[],c:{width:300,height:600,u:658522,I:"",B:20,F:!0,v:!1,C:!1,D:!1,O:!1,
l:[]},contentType:"signal-sovrn",enabled:!0},{o:"8f173059-da06-4911-9469-269d7012c3fc",filters:[],c:{width:728,height:90,u:652112,I:"",B:20,F:!0,v:!1,C:!1,D:!1,O:!1,l:[]},contentType:"signal-sovrn",enabled:!0},{o:"05f29ac0-2df6-40c1-ab63-3cfe7789e55b",filters:[],c:{width:970,height:90,u:652113,I:"",B:20,F:!0,v:!1,C:!1,D:!1,O:!1,l:[]},contentType:"signal-sovrn",enabled:!0},{o:"e0d256dd-ea1d-4130-a652-51e78e5546f9",filters:[],c:{width:970,height:250,u:652114,I:"",B:20,F:!0,v:!1,C:!1,D:!1,O:!1,l:[]},
contentType:"signal-sovrn",enabled:!0},{o:"51c81d2d-f6d7-4b18-8e37-2f5f936ee0b0",filters:[],c:{width:300,height:250,u:652115,I:"",B:20,F:!0,v:!1,C:!1,D:!1,O:!1,l:[]},contentType:"signal-sovrn",enabled:!0}]}],c:{}},b={"signal-sovrn":db};this.m=a;J=na;this.window=M().get();this.P=Ua();this.a=new Za(a,b);b=a.containerId;this.window.__connect=this.window.__connect||{};this.window.__connect.containerIds=this.window.__connect.containerIds||{};this.window.__connect.containerIds[b]||(a=a.containerId,Va(this.P,
this.m.containerId),this.window.__connect.containerIds[a]=!0,eb(this)?fb(this):this.start())}cb.prototype.start=function(){if(-1===this.window.document.URL.indexOf(K().Ha+"=1")?0:-1===document.currentScript.src.indexOf("tag.debug.js")){var a=this.window.document.createElement("script");a.src=document.currentScript.src.replace("tag.min.js","tag.debug.js");this.window.document.head.appendChild(a)}else this.m.c.rb||ta(sa(),{G:this.m.xa.G,containerId:this.m.containerId,ma:this.m.c.ma}),this.a.start()};
function eb(a){var b=a.window;return K().$a.some(function(c){return!b[c]})}function fb(a){var b=a.window.document.createElement("script");b.src=K().ab;b.onload=function(){a.start()};a.window.document.head.appendChild(b)};var S=this&&this.a||function(a,b,c,e){function h(f){return f instanceof c?f:new c(function(d){d(f)})}return new (c||(c=Promise))(function(f,d){function k(g){try{l(e.next(g))}catch(n){d(n)}}function m(g){try{l(e["throw"](g))}catch(n){d(n)}}function l(g){g.done?f(g.value):h(g.value).then(k,m)}l((e=e.apply(a,b||[])).next())})};function T(){this.window=M().get();this.da=new Ia;this.bb=5E3;this.ua=200;this.Ja=2E3;this.ba=K().ba;this.ea=K().ea}var U;
T.prototype.W=function(a,b){return S(this,void 0,void 0,function e(){var h=this,f,d,k;return H(e,function(m){switch(m.a){case 1:a:if(U)var l=U;else{l=a.getAdUnitPath().split("/");for(var g=0;g<l.length;g++){var n=Number(l[g]);if(n){l=U=n;break a}}l=0}l?(l=b.J||[],g=b.l||[],n=b.C||!1,l=!!((b.M||[]).length||l.length||g.length||n)):l=!1;return(f=l)?E(m,gb(h,a),2):m.return(!1);case 2:d=m.b;if(!d.lineItemId){a:{l=b.l||[];for(g=0;g<l.length;g++)if("AD_EXCHANGE"===l[g].type||"ADSENSE"===l[g].type){l=!0;
break a}l=!1}return m.return(l)}m.H=3;return E(m,hb(h,d.lineItemId),5);case 5:return k=m.b,m.return(ib(k,b));case 3:return m.H=0,m.g=null,m.return(!0)}})})};function gb(a,b,c){c=void 0===c?0:c;return S(a,void 0,void 0,function h(){var f=this,d;return H(h,function(k){if(1==k.a){if(c>=f.bb/f.ua)return k.return({});(d=b.getResponseInformation())?(k.a=2,k=void 0):k=E(k,f.wait(f.ua),3);return k}return 2!=k.a?k.return(gb(f,b,++c)):k.return(d)})})}
function hb(a,b){return S(a,void 0,void 0,function e(){var h=this,f,d;return H(e,function(k){switch(k.a){case 1:try{var m=JSON.parse(h.window.localStorage.getItem("connect-"+b));var l=m.expiresAt>Date.now()?m.lineItemInfo:!1}catch(g){l=!1}if(f=l)return k.return(f);if(!jb[b]){k.a=2;break}return E(k,h.wait(200),3);case 3:return E(k,hb(h,b),4);case 4:return k.return(k.b);case 2:return jb[b]=!0,E(k,kb(h,b),5);case 5:return d=k.b,h.ha(b,d),jb[b]=!1,k.return(d)}})})}
T.prototype.ha=function(a,b){b={lineItemInfo:b,expiresAt:Date.now()+1E3*this.ea};try{this.window.localStorage.setItem("connect-"+a,JSON.stringify(b))}catch(c){}};
function kb(a,b){return S(a,void 0,void 0,function e(){var h=this,f,d;return H(e,function(k){switch(k.a){case 1:return f=h.ba+"/"+U+"/"+b,E(k,Ja(h.da,f),2);case 2:d=k.b;if("PENDING"!==d.state){k.a=3;break}return E(k,h.wait(h.Ja),4);case 4:return k.return(kb(h,b));case 3:if("READY"===d.state)return k.return(d);throw Error("Dfp gateway response: "+d.state);}})})}
function ib(a,b){var c;if(!(c=b.J.length?-1===b.J.indexOf(a.orderId):-1<(b.M||[]).indexOf(a.orderId)))a:{c=["ALL","all"];for(var e=q(b.l||[]),h=e.next();!h.done;h=e.next()){var f=h.value;h=a.lineItemType===f.type;var d=c.includes(f.priority);f=a.priority===Number(f.priority);if(h&&(d||f)){c=!0;break a}}c=!1}return c||(b.C?"CREATIVE_SET"===a.roadblockingType:!1)}
T.prototype.wait=function(a){return S(this,void 0,void 0,function c(){return H(c,function(e){return e.return(new Promise(function(h){return setTimeout(h,a)}))})})};var jb={};function lb(a,b){var c=a.wa||10;return mb(a).some(function(e){var h=Math.abs(b.height-e.height)<c;return Math.abs(b.width-e.width)<c&&h})}function nb(a){return mb(a).reduce(function(b,c){return b.width*b.height<c.width*c.height?c:b},{width:0,height:0})}function ob(a){return(a=pb(a,"iframe")||pb(a,"img"))?a.getBoundingClientRect():{width:0,height:0}}
function pb(a,b){a=q(a.getElementsByTagName(b));for(b=a.next();!b.done;b=a.next()){b=b.value;var c=b.getBoundingClientRect();if(c.width&&c.height)return b}}function mb(a){return a.sizes?a.sizes.map(function(b){b=b.split("x");return{width:Number(b[0]),height:Number(b[1])}}):[{height:a.height,width:a.width}]};var qb=this&&this.a||function(a,b,c,e){function h(f){return f instanceof c?f:new c(function(d){d(f)})}return new (c||(c=Promise))(function(f,d){function k(g){try{l(e.next(g))}catch(n){d(n)}}function m(g){try{l(e["throw"](g))}catch(n){d(n)}}function l(g){g.done?f(g.value):h(g.value).then(k,m)}l((e=e.apply(a,b||[])).next())})};function W(){this.window=M().get();this.jb=new T;this.window.googletag=this.window.googletag||{};this.window.googletag.cmd=this.window.googletag.cmd||[]}
W.prototype.a=function(a,b){var c=this;if(!rb(this))return this.window.setTimeout(this.a.bind(this,a,b),500),null;if(a.D)return sb(this,"impressionViewable",b);tb(this).forEach(function(e){e=ub(e);vb(c,e)&&b(e)});sb(this,"slotRenderEnded",b)};W.prototype.W=function(a,b){return qb(this,void 0,void 0,function e(){var h=this,f;return H(e,function(d){if(1==d.a)return rb(h)?(d.a=2,d=void 0):d=E(d,h.wait(200),3),d;if(2!=d.a)return d.return(h.W(a,b));f=wb(h,a);return d.return(h.jb.W(f,b))})})};
function wb(a,b){return tb(a).filter(function(c){return b===ub(c)})[0]}function sb(a,b,c){a.window.googletag.cmd.push(function(){a.window.googletag.pubads().addEventListener(b,function(e){e=ub(e.slot);vb(a,e)&&c(e)})})}function rb(a){a=a.window.googletag;return!!a&&a.pubadsReady}function vb(a,b){a=a.window.document.querySelector("#"+b);if(!a)return!1;a=ob(a);return 50<=a.width&&50<=a.height}function tb(a){return a.window.googletag.pubads().getSlots()}
function ub(a){a=a.getSlotElementId();!isNaN(Number(parseInt(a.charAt(0))))&&(a="\\3"+a.charAt(0)+" "+a.slice(1));return a.replace(/\//g,"\\/").replace(/\./g,"\\.")}W.prototype.wait=function(a){return qb(this,void 0,void 0,function c(){return H(c,function(e){return e.return(new Promise(function(h){return setTimeout(h,a)}))})})};function xb(){this.window=M().get()}function yb(a,b,c){c=void 0===c?.5:c;if(a.window.za&&"SAFEFRAME"===a.window.za.state)return a.window.ja.ext.vb()/100>=c;b=b.getBoundingClientRect();var e=a.window.innerWidth;a=a.window.innerHeight;return(Math.max(0,Math.min(b.right,e))-Math.max(0,Math.min(b.left,e)))*(Math.max(0,Math.min(b.bottom,a))-Math.max(0,Math.min(b.top,a)))/(b.width*b.height)>=c};function zb(){this.window=M().get();this.a=new xb;this.b=Da();this.R={};Ab(this)}var Bb;zb.prototype.ia=function(a,b,c,e){var h=a.id;this.R[h+c]||(this.R[h+c]={o:c,element:a,ta:b,ca:0,ga:0,sa:0,Ya:e})};
function Ab(a){a.window.setInterval(function(){for(var b=q(Object.keys(a.R)),c=b.next();!c.done;c=b.next()){c=a.R[c.value];var e;if(!(e=!c.N)){a:{for(e=c.N;e.parentNode;)if(e=e.parentNode,e===c.element){e=!0;break a}e=!1}e=!e}e&&(e=Cb(c.element,"iframe"),c.N=e||Cb(c.element,"img"));var h=c.N?c.N:c.element;c.ga++;e=yb(a.a,h,c.ta.K);a.b.s()&&e&&c.ca++;e=c.ta;h=yb(a.a,h,e.K);var f=c.ca>=e.B,d=c.ga>=e.fa;e=c.sa>=e.$;h&&f&&!e&&d&&(c.Ya(c.element),c.sa++,c.ca=0,c.ga=0,c.N=null)}},1E3)}
function Cb(a,b){a=a.getElementsByTagName(b);for(b=0;b<a.length;b++){var c=a[b].getBoundingClientRect();if(c.width&&c.height)return a[b]}};var Db=this&&this.a||function(a,b,c,e){function h(f){return f instanceof c?f:new c(function(d){d(f)})}return new (c||(c=Promise))(function(f,d){function k(g){try{l(e.next(g))}catch(n){d(n)}}function m(g){try{l(e["throw"](g))}catch(n){d(n)}}function l(g){g.done?f(g.value):h(g.value).then(k,m)}l((e=e.apply(a,b||[])).next())})};function X(a){this.c=a;Bb||(Bb=new zb);this.ra=Bb;this.oa=new W;this.window=M().get();a.aa=a.aa||[];a.l=a.l||[];a.J=a.J||[];a.M=a.M||[];a.K=a.K||.5}
X.prototype.start=function(a){var b=this;Eb(this,function(c,e){if(!b.c.F)return Fb(b,c,a);Gb(b,c,e,a)})};function Eb(a,b){if(a.c.F)a.oa.a({D:a.c.D},function(e){b("#"+e,e)});else{a=q(a.c.I);for(var c=a.next();!c.done;c=a.next())b(c.value)}}
function Gb(a,b,c,e){Db(a,void 0,void 0,function f(){var d=this,k,m;return H(f,function(l){if(1==l.a){a:{var g=q(d.c.aa);for(var n=g.next();!n.done;n=g.next()){if((n=d.querySelector(d.window.document,n.value))&&n.id===c){g=!0;break a}if(d.querySelector(n,"#"+c)){g=!0;break a}}g=!1}g||((g=d.querySelector(d.window.document,b))?(g=ob(g),g=!d.c.sizes&&-1!==(d.c.Bb||[]).indexOf(g.width+"x"+g.height)||d.c.sizes&&!lb(d.c,g)?!0:!1):g=!0);if(g)return l.return();k=Fb(d,b,e);return E(l,Hb(d,c),2)}(m=l.b)||delete d.ra.R[k.id+
d.c.o];l.a=0})})}function Fb(a,b,c){var e=a.querySelector(a.window.document,b),h={K:a.c.K,B:a.c.B,$:a.c.$,fa:K().fa};if(e)return a.ra.ia(e,h,a.c.o,a.a.bind(a,c,b)),e}function Hb(a,b){return Db(a,void 0,void 0,function e(){var h=this;return H(e,function(f){return 1==f.a?Ib(h)?E(f,h.oa.W(b,h.c),2):f.return(!0):f.return(!f.b)})})}
X.prototype.a=function(a,b,c){return Db(this,void 0,void 0,function h(){var f=this,d;return H(h,function(k){if(1==k.a)return E(k,a(f.c.o,b,c),2);if(d=k.b){var m=f.querySelector(c,"iframe"),l=nb(f.c),g=l.width;l=l.height;m.style.width=d.width+"px";m.style.height=d.height+"px";m.style.marginTop=(l-d.height)/2+"px";m.style.marginLeft=(g-d.width)/2+"px"}k.a=0})})};function Ib(a){return[0<a.c.l.length,0<a.c.M.length,0<a.c.J.length,!!a.c.C].some(function(b){return!!b})}
X.prototype.querySelector=function(a,b){if(!a)return null;try{return a.querySelector(b)}catch(c){return null}};function Y(){this.i={append:this.b.bind(this),prepend:this.g.bind(this),before:this.f.bind(this),after:this.a.bind(this)};this.window=M().get()}
Y.prototype.get=function(a){var b=null;try{b=this.window.document.querySelector(a.hb)}catch(d){this.window.console.log("Sovrn Connect Error:",d.message)}if(b){var c=a.method||"append",e=a.width,h=a.height;a=a.Ga||{};var f=this.window.document.createElement("div");f.setAttribute("class","sovrn-connect-ad");f.setAttribute("id","connect-wrapper-"+Jb++);f.style.width=e+"px";f.style.height=h+"px";f.style.margin="0 auto";Kb(a,f);this.i[c](b,f);b=f}else b=null;return b};
function Kb(a,b){Object.keys(a).forEach(function(c){b.style[c]=a[c]})}Y.prototype.b=function(a,b){a.appendChild(b)};Y.prototype.g=function(a,b){a.insertBefore(b,a.firstChild)};Y.prototype.f=function(a,b){a.parentNode.insertBefore(b,a)};Y.prototype.a=function(a,b){a.parentNode.insertBefore(b,a.nextSibling)};var Jb=0;var Lb=this&&this.a||function(a,b,c,e){function h(f){return f instanceof c?f:new c(function(d){d(f)})}return new (c||(c=Promise))(function(f,d){function k(g){try{l(e.next(g))}catch(n){d(n)}}function m(g){try{l(e["throw"](g))}catch(n){d(n)}}function l(g){g.done?f(g.value):h(g.value).then(k,m)}l((e=e.apply(a,b||[])).next())})};function Mb(){this.window=M().get();this.a=!1;this.j=K()}
Mb.prototype.get=function(){return Lb(this,void 0,void 0,function b(){var c=this,e;return H(b,function(h){e=c;Nb(c);return h.return(new Promise(function(f){return Ob(e,f)}))})})};function Ob(a,b){if(Pb(a))return b(a.window.$sf.host);setTimeout(function(){Ob(a,b)},500)}function Nb(a){if(!a.window.$sf&&!a.a){a.a=!0;var b=a.window.document.createElement("script");b.setAttribute("src",a.j.va.Wa);a.window.document.body.appendChild(b)}}function Pb(a){return(a=a.window.$sf)&&a.host&&a.host.boot?!0:!1};var Qb=this&&this.a||function(a,b,c,e){function h(f){return f instanceof c?f:new c(function(d){d(f)})}return new (c||(c=Promise))(function(f,d){function k(g){try{l(e.next(g))}catch(n){d(n)}}function m(g){try{l(e["throw"](g))}catch(n){d(n)}}function l(g){g.done?f(g.value):h(g.value).then(k,m)}l((e=e.apply(a,b||[])).next())})};function Z(){this.window=M().get();this.fb=new Mb;this.b=null;this.a={};this.j=K()}
function Rb(a,b,c){return Qb(a,void 0,void 0,function h(){var f=this,d;return H(h,function(k){d=f;return k.return(new Promise(function(m){return Qb(d,void 0,void 0,function g(){var n=this,p,u;return H(g,function(y){if(1==y.a)return E(y,n.fb.get(),2);p=y.b;u={width:b.width,height:b.height,adCode:b.Ba||n.V(b)};return y.return(Sb(n,p,u,c,m))})})}))})})}Z.prototype.V=function(a){return'<script src="'+(""+this.j.ka+a.u+"&width="+a.width+"&height="+a.height+"&iv="+a.X)+'">\x3c/script>'};
function Sb(a,b,c,e,h){var f=e.id+"-safe-frame",d=a.window.document.createElement("div");d.setAttribute("id",f);e.appendChild(d);a.a[f]={placeholder:e,resolve:h};a.b||(a.b=new b.Config({auto:!1,renderFile:a.j.va.Ta,onEndPosRender:a.g.bind(a)}));e=new b.PosConfig({id:f,dest:f,w:c.width,h:c.height});b.render(new b.Position(f,c.adCode,null,e));b=a.a[f];b.pa=0;b.qa=a.window.setInterval(a.f.bind(a,f,b),500)}
Z.prototype.g=function(a){var b=this.a[a],c=b.placeholder.querySelector("#"+a);c.setAttribute("title","sovrn-ad");this.window.clearInterval(b.qa);b.resolve(c);delete this.a[a]};Z.prototype.f=function(a,b){if(a=this.window.document.getElementById(a))a.dispatchEvent(Tb(this)),a.style.display="block",a.style.visibility="inherit",b.resolve(a);b.pa++;10<b.pa&&this.window.clearInterval(b.qa)};
function Tb(a){if("function"===typeof a.window.Event)return new a.window.Event("load");a=a.window.document.createEvent("CustomEvent");a.initCustomEvent("load",!1,!1,void 0);return a};function Ub(){this.window=M().get()}Ub.prototype.create=function(a){var b=this.window.document.createElement("iFrame");b.height=""+a.height;b.width=""+a.width;b.setAttribute("frameBorder","0");b.setAttribute("scrolling","no");b.setAttribute("marginwidth","0");b.setAttribute("marginheight","0");b.setAttribute("title","sovrn-ad");return b};var Vb=this&&this.a||function(a,b,c,e){function h(f){return f instanceof c?f:new c(function(d){d(f)})}return new (c||(c=Promise))(function(f,d){function k(g){try{l(e.next(g))}catch(n){d(n)}}function m(g){try{l(e["throw"](g))}catch(n){d(n)}}function l(g){g.done?f(g.value):h(g.value).then(k,m)}l((e=e.apply(a,b||[])).next())})};function Wb(a){this.c=a;this.window=M().get();this.gb=new Z;this.Ua=new Ub;this.protocol=this.window.location.protocol;this.j=K()}
function Xb(a,b){var c=!0;c=void 0===c?!1:c;return new Promise(function(e){return Vb(a,void 0,void 0,function f(){var d=this,k,m,l,g;return H(f,function(n){if(1==n.a){k=d.Ua.create(d.c);b.appendChild(k);m=k.contentDocument;l=Yb(d.c,c);if(!d.c.v){n.a=2;return}g=Object.assign(Object.assign({},d.c),{Ba:d.V(l)});return E(n,Rb(d.gb,g,k.parentNode),3)}if(2!=n.a)return b.removeChild(b.querySelector("iframe")),n.return(e());m.open();m.write(d.V(l));setTimeout(function(){m.close();return e()},0);n.a=0})})})}
Wb.prototype.V=function(a){return'<script src="'+(this.j.ka+a.u+"&width="+a.width+"&height="+a.height+"&iv="+a.X)+'">\x3c/script>'};function Yb(a,b){return{u:a.u,width:a.width,height:a.height,X:b?"reload":a.X}};var Zb=this&&this.b||function(a,b,c,e){var h=arguments.length,f=3>h?b:null===e?e=Object.getOwnPropertyDescriptor(b,c):e,d;if("object"===typeof Reflect&&"function"===typeof Reflect.Ia)f=Reflect.Ia(a,b,c,e);else for(var k=a.length-1;0<=k;k--)if(d=a[k])f=(3>h?d(f):3<h?d(b,c,f):d(b,c))||f;return 3<h&&f&&Object.defineProperty(b,c,f),f},$b=this&&this.f||function(a,b){if("object"===typeof Reflect&&"function"===typeof Reflect.Z)return Reflect.Z(a,b)},ac=this&&this.a||function(a,b,c,e){function h(f){return f instanceof
c?f:new c(function(d){d(f)})}return new (c||(c=Promise))(function(f,d){function k(g){try{l(e.next(g))}catch(n){d(n)}}function m(g){try{l(e["throw"](g))}catch(n){d(n)}}function l(g){g.done?f(g.value):h(g.value).then(k,m)}l((e=e.apply(a,b||[])).next())})};
function bc(a,b){this.c=a;var c={height:a.height,width:a.width,u:a.u,v:a.v,G:a.G,X:""};this.ib=new X({o:b,F:a.F,I:[a.I],B:a.B,$:a.$,K:a.K,D:a.D,l:a.l,J:a.J,M:a.M,C:a.C,aa:a.aa,sizes:[a.width+"x"+a.height],wa:a.wa});this.kb=new Wb(c);this.Za=new Y;this.Ca=sa();this.P=Ua()}
bc.prototype.ya=function(a,b,c){return ac(this,void 0,void 0,function h(){var f=this,d,k,m,l,g;return H(h,function(n){if(1==n.a){for(var p=c.childNodes,u=p.length;0<u;u--)c.removeChild(p[u-1]);d={hb:b,width:f.c.width,height:f.c.height,Ga:f.c.pb};k=f.Za.get(d);m=f.c;l=m.G;g=m.u;return E(n,Xb(f.kb,k),2)}p=f.c.height;p=(k.getBoundingClientRect().height-p)/2;k.style.paddingTop=p+"px";k.style.paddingBottom=p+"px";ua(f.Ca,l,"#"+k.id,g);f.P.L.push(Object.assign({},{contentId:a,type:"activation"}));n.a=0})})};
var db=bc;db=Zb([function(a){function b(){var c=a.apply(this,arguments)||this;c.La=!1;return c}w(b,a);return b},$b("design:paramtypes",[Object,Object])],db);new cb;}).call({})
/* 
date-of-deployment: UTC2021-02-02T11:48:07Z 
contents:
@connect/underground-signal-sovrn-content: 2.3.0
filters:
container:
@connect/underground-container: 2.5.6
*/